pull_request_rules:
  - name: Automatic merge on successful build
    conditions:
      - check-success=build
    actions:
      merge:
        method: merge
      delete_head_branch:
  - name: Assign pull request to 5h15h4k1n9
    actions:
      assign:
        add_users:
          - 5h15h4k1n9