spring:
  datasource:
    url: jdbc:h2:file:./data/submissions                 # Path to database
    driver-class-name: org.h2.Driver                     # Database driver
    username: sa                                         # Username to login
    password: password                                   # Password to login
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect   # Hibernate dialect
    defer-datasource-initialization: true                # Initialising database
    generate-ddl: true                                   # Autogenerate database if it's not exist
    open-in-view: true                                   # Helps to work in multithreading
  h2:
    console:
      enabled: true                                      # Enabling h2 console
      path: /h2-console                                  # Path to h2 database console
      settings:
        web-allow-others: true                           # Allows getting access to db while application is running
logging:
  file:
    name: "logs/server.log"                              # Path to log file
  logback:
    rollingpolicy:
      clean-history-on-start: false                      # Not cleaning history on start
      max-history: 31                                    # Stores a month of logs
server:
  ssl:
    key-store: classpath:keystore/grading-system.p12
    key-store-type: pkcs12
    key-alias: grading-system
    key-store-password: qwerty123456
    enabled: true
  port: 8080